# PROTOTYPE
# These types are meant to be generated based on the content model.

DomainContent:
    type: "interface"
    config:
        fields:
            _content:
                description: "Underlying content item"
                type: "Content"
            _location:
                description: "The content's main location"
                type: "Location"
            _allLocations:
                description: "All the content's locations"
                type: "[Location]"
            # Should be limited to containers

        resolveType: "@=resolver('DomainContentType', [value])"

DomainContainerContent:
    type: "interface"
    config:
        fields:
            _children:
                description: "Children of the content's locations"
                type: "[DomainContent]"
                resolve: "@=resolver('DomainContentChildren', [value, args])"
                args:
                    mainLocationOnly:
                        type: Boolean
                    recursive:
                        type: Boolean
            _childrenByType:
                description: "Children of the content's locations, grouped by type"
                type: "[Domain]"
                resolve: "@=[value, args]"
                args:
                    mainLocationOnly:
                        type: Boolean
                    recursive:
                        type: Boolean
