services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    BD\EzPlatformGraphQLBundle\DomainContent\RepositoryDomainGenerator:
        calls:
            - [addWorker, ['@BD\EzPlatformGraphQLBundle\DomainContent\SchemaWorker\ContentTypeGroup\DefineDomainGroup']]
            - [addWorker, ['@BD\EzPlatformGraphQLBundle\DomainContent\SchemaWorker\ContentTypeGroup\AddDomainGroupToDomain']]
            - [addWorker, ['@BD\EzPlatformGraphQLBundle\DomainContent\SchemaWorker\ContentType\DefineDomainContent']]
            - [addWorker, ['@BD\EzPlatformGraphQLBundle\DomainContent\SchemaWorker\ContentType\AddDomainContentToDomainGroup']]
            - [addWorker, ['@BD\EzPlatformGraphQLBundle\DomainContent\SchemaWorker\FieldDefinition\AddFieldDefinitionToDomainContent']]
            - [addWorker, ['@BD\EzPlatformGraphQLBundle\DomainContent\SchemaWorker\ContentType\AddContentTypeToContentTypeIdentifierList']]

    BD\EzPlatformGraphQLBundle\DomainContent\NameHelper: ~

    _instanceof:
        BD\EzPlatformGraphQLBundle\DomainContent\SchemaWorker\BaseWorker:
            calls:
                - [setNameHelper, ['@BD\EzPlatformGraphQLBundle\DomainContent\NameHelper']]

    BD\EzPlatformGraphQLBundle\DomainContent\SchemaWorker\ContentType\DefineDomainContent: ~

    BD\EzPlatformGraphQLBundle\DomainContent\SchemaWorker\ContentType\AddDomainContentToDomainGroup: ~

    BD\EzPlatformGraphQLBundle\DomainContent\SchemaWorker\ContentTypeGroup\DefineDomainGroup: ~

    BD\EzPlatformGraphQLBundle\DomainContent\SchemaWorker\ContentTypeGroup\AddDomainGroupToDomain: ~

    BD\EzPlatformGraphQLBundle\DomainContent\SchemaWorker\FieldDefinition\AddFieldDefinitionToDomainContent: ~

    BD\EzPlatformGraphQLBundle\DomainContent\SchemaWorker\ContentType\AddContentTypeToContentTypeIdentifierList: ~